### PR TITLE
some doc

### PR DESCRIPTION
**Pull request by hpzorn**
Added some scaladoc, renamed some variables to make code a bit more accessible for new developers.

### CODE REVIEW

**Comment by utzwestermann** [comment]
Your changing of packages breaks existing views, in particular within the tutorial. This will also require quite a bit of adaptation of existing view code at Otto. Really necessary?

**Comment by utzwestermann** [comment]
Apart from that, laudable effort :-)

But maybe we can keep the package structure?

**Comment by hpzorn** [comment]
I'll have a look at the failing test, worked for me locally after disabling one of them (didn't work on the mac).

The reason for moving StorageFormats and Messages to subpackages was that they will get listed as a seperate section in Scaladoc, which makes it much more readable. Otherwise all messages are listed between the classes containing logic in the index.

I can leave out the renaming though, it shouldn't be difficult to adopt. You just need to fix the import. The tutorial built for me. Have to have a look, changes in the tutorial didn't make it to the commit.

If you want me to remove the package-renaming, I will close re-open the pullrequest.

**Comment by utzwestermann** [comment]
OK, make the build and tests pass and I will accept the request. Can keep the package renaming in as I might do some API breaking changes as well so we might have it all in one big change

**Comment by utzwestermann** [comment]
I am going to close the request, you reopen it once build is working again

**Pull request closed without merging**
