### PR TITLE
Hive 1.1.x support

### LINKED ISSUE #6: Migrate to Hive 1.1.0
For historical reasons, local testing still uses the old HiveServer (not HiveServer2), which is not part of Hive 1.1.0 any more. Please update to HiveServer2; and check side-effects with Minioozie as well.

### PR DESCRIPTION
**Pull request by hpzorn**
Migrates to hive 1.1.0. 
Needed to adapt ViewSerde since Hive now serializes Maps using : as separator. The proper solution would be to use a JSON deserializer in ViewSerde since the current implementation will fail if either a colon, an equals sign or double quotes appears in keys or values.

Closes #6

### CODE REVIEW

**Comment by hpzorn** [comment]
Ok, we actually have tests with ":" inside a map. Probably will need to integrate a JSONParser then. Or adapt the tutorial not use ":" as a seperator in tests. 

Moreover the missing HCatLoader problem does not occur locally for me. I will investigate amend the PR tomorrow.

**Comment by utzwestermann** [comment]
Can't we go for good old \001 \002 \003 separators? We control serialization and the textformat parameterization.

**Comment by hpzorn** [comment]
merged with master

**Comment by utzwestermann** [comment]
Took it over in my fork for some final validations and changes and will merge from there.

Good job!!

**Pull request closed without merging**
